run:
  timeout: 5m
  tests: true  # Run linters on test files

linters:
  enable:
    - errcheck      # Check error returns
    - gosimple      # Simplify code
    - govet         # Suspicious constructs
    - ineffassign   # Unused assignments
    - staticcheck   # Static analysis
    - unused        # Unused code
    - gofmt         # Formatting
    - goimports     # Import organization
    - misspell      # Spelling errors
    - gocritic      # Code quality

linters-settings:
  errcheck:
    check-blank: true
    # Exclude common cleanup patterns in tests and defers
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (*net/http.Response.Body).Close

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam     # Allow large params by value (will fix in comprehensive cleanup)
      - unnamedResult # Allow unnamed results (will fix in comprehensive cleanup)

  staticcheck:
    checks: ["all", "-SA1029", "-SA4008", "-SA9003"]
    # SA1029: Context key should not be built-in type (test simplicity)
    # SA4008: Loop condition never changes (acceptable in some patterns)
    # SA9003: Empty branch (acceptable for deferred cleanup with logging)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude specific patterns that are acceptable
  exclude-rules:
    # Allow unchecked errors in test cleanup (defer Close, Shutdown, etc.)
    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value.*is not checked"
      source: "defer.*Close\\(\\)|defer.*Shutdown\\("

    # Allow context.WithValue with string keys in tests (matches implementation)
    - path: _test\.go
      linters:
        - staticcheck
      text: "SA1029.*should not use built-in type"

    # Allow empty branches with comments explaining best-effort
    - linters:
        - staticcheck
      text: "SA9003.*empty branch"
      source: "// (Log|Best effort)"
